name: Elixir CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    uses: bennydreamtech23/precheck-developer/.github/workflows/elixir-ci.yml@master
    with:
      elixir_version: "1.19.5"
      otp_version: "28"
